### PR TITLE
Add UI to the calculator app

### PR DESCRIPTION
**Pull request by rachaouldbabaali**
In this Pull Request, I have : 

- [x]  Created a new directory called components.

- [x]  Create a new Calculator.js file inside components.

- [x]  Created a React component that matches the wireframe design:
- [x] Implemented the design using only (JSX and CSS)

### CODE REVIEW

**Review by Ibizugbe — CHANGES_REQUESTED** [review]
Hi @rachaouldbabaali 👋👋, 

tryagain


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅

- [x] Linters are correctly setup and they are passing.👍
- [x] gitflow have been used👍.
- [x] The `components` directory have been created with the `calculator` component added to it👍.


## Required Changes ♻️

- [ ] Nice job so far👍. currently, you still have some boiler plates from CRA and it is a requirement in this milestone that you delete all the boilerplate from CRA😉 
image


and you still have some of them in your public directory, kindly take them away😉😉
image

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rachaouldbabaali** [comment]
Thank @Ibizugbe, I truly appreciate your time and effort in reviewing my work. boilerplate from CRA from the public folder has been deleted 👍🏻

**Review by divinecharlotte — APPROVED** [review]
# Hello @rachaouldbabaali   😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯

- Descriptive pr👍 
- Linters are passing👍 
 




## Congratulations! 🎉 



Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rachaouldbabaali** [comment]
Thank you @divinecharlotte I truly appreciate your time and effort in reviewing my work

**Pull request merged**
